### PR TITLE
Moved imagedims to OL8 base image

### PR DESCRIPTION
**Pull request by metamemelord**
Added OL8 based function for imagedims

### CODE REVIEW

**Comment by sachin-pikle** [comment]
@metamemelord I am merging this PR. Please leave a comment here once the new Fn Python FDK OL8 slim base images are available in docker hub.

**Comment by sachin-pikle** [comment]
@metamemelord I noticed one small thing in the readme. It says "The Dockerfile that "fn build" would automatically generate to build a Python 3.6 function container image looks like this:" but the Dockerfile shown has the image magick installation steps. We should show the default Fn-generated Dockerfile as-is first before adding the custom steps for image magick.

**Comment by metamemelord** [comment]
Thanks for bringing that to my notice, I will change the documentation to reflect correct information.

**Comment by sachin-pikle** [comment]
Hi @metamemelord I tested your changes and here's my feedback. This is what the final Dockerfile should look like:

```
FROM fnproject/python:3.6-dev as build-stage
WORKDIR /function
ADD requirements.txt /function/

RUN pip3 install --target /python/  --no-cache --no-cache-dir -r requirements.txt &&\
  rm -fr ~/.cache/pip /tmp* requirements.txt func.yaml Dockerfile .venv &&\
  chmod -R o+r /python
ADD . /function/
RUN rm -fr /function/.pip_cache

FROM fnproject/python:3.6
RUN microdnf install oracle-epel-release-el8 &&\
      microdnf install ImageMagick &&\
      microdnf remove oracle-epel-release-el8 &&\
      microdnf clean all
WORKDIR /function
COPY --from=build-stage /python /python
COPY --from=build-stage /function /function
RUN chmod -R o+r /function
ENV PYTHONPATH=/function:/python
ENTRYPOINT ["/python/bin/fdk", "/function/func.py", "handler"]
```

**Comment by sachin-pikle** [comment]
@metamemelord can you please review my changes and confirm?

**Comment by metamemelord** [comment]
Yes, I fixed the dockerfile. I tested the function locally and it is working fine.

**Comment by sachin-pikle** [comment]
I think your changes accidentally overwrote mine :-) I will add mine back and merge the PR. Please check the diff.

**Pull request merged**
